baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'YoYo Site'
theme = 'ananke'
canonifyURLs = true
# disqusShortname = "YoYo"
[params]
  custom_css = ["custom.css"]

[params.utterances]  # https://utteranc.es/
owner = "xia7139" # Your GitHub ID
repo = "yoyo_comment"              # The repo to store comments
