baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'YoYo Site'
theme = 'ananke'
canonifyURLs = true
disqusShortname = "YoYo"
[params]
  commentoEnable = true
  custom_css = ["custom.css"]
